# Generated by Django 4.1.7 on 2023-04-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_likepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_image',
            field=models.ImageField(default='blank-profile-picture.png', upload_to=''),
        ),
    ]
