# Generated by Django 4.1.7 on 2023-04-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_image',
            field=models.ImageField(default='blank-profile-picture.png', upload_to=''),
        ),
    ]
