# Generated by Django 4.1.7 on 2023-04-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_image',
        ),
    ]
